### ISSUE TITLE
 Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by Gcuje** [lucxsm/assettobot#3]
Hello,
I wanted to try the bot but it stop working after few minutes with this error : 
```
/home/ubuntu/bot/assettobot/src/scheduler.js:44
        if (embed && embed.author.name.startsWith('Leaderboard')) {
                                  ^

TypeError: Cannot read properties of null (reading 'name')
    at /home/ubuntu/bot/assettobot/src/scheduler.js:44:35
    at Array.filter (<anonymous>)
    at Object.updateLeaderboards (/home/ubuntu/bot/assettobot/src/scheduler.js:40:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout._onTimeout (/home/ubuntu/bot/assettobot/src/index.js:71:5)
```
However, I managed to add a server with the "addserver" command before it stopped and I received a message successfully created in my discord channel.
Am i missing something or doing something wrong? Thank you for your help !

**Comment by lucxsm** [comment]
I think its
